CNL: cnl Namespace Reference
cnl Namespace Reference
compositional numeric library
Namespaces
literals
user-defined literals
Classes
struct constant
type whose value is also its non-type template parameter
class elastic_integer
An integer type with auto-widening operators.
class fixed_point
literal real number approximation that uses fixed-point arithmetic
struct fractional
numeric type represented as the fraction, numerator / denominator
struct from_rep
generic function object that returns the number encapsulating a given value
struct from_rep< elastic_integer< Digits, Narrowest > >
elastic_integer specialization of from_rep
struct from_rep< fixed_point< ArchetypeRep, Exponent, Radix > >
fixed_point specialization of from_rep
struct from_rep< Number, _impl::enable_if_t< cnl::is_integral< Number >::value > >
Specialization of from_rep for integer types.
struct from_rep< overflow_integer< ArchetypeRep, OverflowTag > >
overflow_integer specialization of from_rep
struct from_rep< rounding_integer< ArchetypeRep, RoundingTag > >
rounding_integer specialization of from_rep
class overflow_integer
An integer which detects overflow.
class rounding_integer
An integer with customized rounding behavior.
struct set_digits
convert a type to a similar type with the given number of digits
Typedefs
template<int Digits, int Exponent = 0, class Narrowest = signed>
using elastic_number = fixed_point< elastic_integer< Digits, Narrowest >, Exponent >
literal real number approximation that uses fixed-point arithmetic and auto-widens to avoid overflow
template<unsigned NumDigits = digits<int>::value>
using multiprecision = signed_multiprecision< NumDigits >
alias to a signed, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
template<class T , _digits_type Digits>
using set_digits_t = typename set_digits< T, Digits >::type
Alias to cnl::set_digits.
template<unsigned NumDigits = digits<int>::value>
using signed_multiprecision = _sized_integer_impl::number< NumDigits+1, _bmp::signed_magnitude >
alias to a signed, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
template<int Digits = digits<int>::value, class RoundingTag = nearest_rounding_tag, class OverflowTag = trapping_overflow_tag, class Narrowest = int>
using static_integer = _impl::static_integer< Digits, RoundingTag, OverflowTag, Narrowest >
a general-purpose integer type
template<int Digits, int Exponent = 0, class RoundingTag = nearest_rounding_tag, class OverflowTag = trapping_overflow_tag, class Narrowest = signed>
using static_number = fixed_point< _impl::static_integer< Digits, RoundingTag, OverflowTag, Narrowest >, Exponent >
a general-purpose fixed-point real number type
template<unsigned NumDigits = digits<unsigned>::value>
using unsigned_multiprecision = _sized_integer_impl::number< NumDigits, _bmp::unsigned_magnitude >
alias to an unsigned, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
Functions
template<typename Rep , int Exponent, int Radix>
constexpr auto abs (fixed_point< Rep, Exponent, Radix > const &x) noexcept -> decltype(-x)
absolute value
template<class Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > exp2 (fixed_point< Rep, Exponent > x)
Calculates exp2(x), i.e. 2^xAccurate to 1LSB for up to 32 bit underlying representation.
template<typename Narrowest = int, CNL_IMPL_CONSTANT_VALUE_TYPE Value = 0>
constexpr elastic_number< _impl::max(digits< constant< Value >>::value-trailing_bits(Value), 1), trailing_bits(Value), Narrowest > make_elastic_number (constant< Value >)
generate an cnl::elastic_number object of given value
template<class Narrowest = int, class Integral = int>
constexpr elastic_number< numeric_limits< Integral >::digits, 0, Narrowest > make_elastic_number (Integral value)
generate an cnl::elastic_number object of given value
template<typename Value >
constexpr auto make_fixed_point (Value const &value) -> cnl::from_value_t< fixed_point< Value, 0 >, Value >
makes a fixed_point object from a given value
template<typename Numerator , typename Denominator >
constexpr fractional< Numerator, Denominator > make_fractional (Numerator const &n, Denominator const &d)
creates a fractional value with types deduced from the numerator and denominator
template<typename Numerator >
constexpr fractional< Numerator, Numerator > make_fractional (Numerator const &n)
creates a fractional value with types deduced from the numerator
template<class RoundingTag = nearest_rounding_tag, class OverflowTag = trapping_overflow_tag, class Narrowest = signed, class Input = int>
static_number< numeric_limits< Input >::digits, 0, RoundingTag, OverflowTag, Narrowest > constexpr make_static_number (Input const &input)
constructs a static_number from a given variable
template<class RoundingTag = rounding_integer<>::rounding, class OverflowTag = overflow_integer<>::overflow_tag, class Narrowest = int, class Input = int, CNL_IMPL_CONSTANT_VALUE_TYPE Value>
static_number< _impl::used_digits(Value) -trailing_bits(Value), trailing_bits(Value), RoundingTag, OverflowTag, Narrowest > constexpr make_static_number (constant< Value > const &)
constructs a static_number from a given constant value
template<class Lhs , class Rhs >
constexpr auto multiply (Lhs const &lhs, Rhs const &rhs) -> typename _multiply_impl::params< Lhs, Rhs >::result_type
calculates the product of two fixed_point factors
template<class Quotient = _impl::default_quotient_tag, class Dividend , class Divisor >
constexpr auto quotient (Dividend const &dividend, Divisor const &divisor) -> typename _impl::result< Quotient, Dividend, Divisor >::type
calculates the quotient of two fixed_point values
template<typename Rep , int Exponent, int Radix>
constexpr fixed_point< Rep, Exponent, Radix > sqrt (fixed_point< Rep, Exponent, Radix > const &x)
calculates the square root of a fixed_point value
template<typename Rep , int Exponent, int Radix>
constexpr Rep to_rep (fixed_point< Rep, Exponent, Radix > const &number)
fixed_point overload of to_rep(Number const& number)
template<int Digits, class Narrowest >
constexpr auto to_rep (elastic_integer< Digits, Narrowest > &number) -> typename elastic_integer< Digits, Narrowest >::rep &
Overload of to_rep(Number const& number) for elastic_integer.
template<class Rep , class RoundingTag >
constexpr Rep & to_rep (rounding_integer< Rep, RoundingTag > &number)
Overload of to_rep(Number const& number) for rounding_integer.
template<class Rep , class OverflowTag >
constexpr Rep & to_rep (overflow_integer< Rep, OverflowTag > &number)
Overload of to_rep(Number const& number) for overflow_integer.
template<class Number >
constexpr Number to_rep (Number const &number)
Returns the value encapsulated in number.
Variables
template<typename T >
constexpr T apery {_impl::deleted_fn<T>()}
approximation of Apéry's constant; primary variable template
template<>
constexpr double apery< double > {1.202056903159594285399738161511449990}
specialization of cnl::apery for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > apery< fixed_point< Rep, Exponent > >
specialization of cnl::apery for cnl::fixed_point
template<>
constexpr float apery< float > {1.202056903159594285399738161511449990f}
specialization of cnl::apery for float
template<>
constexpr long double apery< long double > {1.202056903159594285399738161511449990L}
specialization of cnl::apery for long double
template<typename T >
constexpr T catalan {_impl::deleted_fn<T>()}
approximation of Catalan's constant; primary variable template
template<>
constexpr double catalan< double > {0.915965594177219015054603514932384110774}
specialization of cnl::catalan for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > catalan< fixed_point< Rep, Exponent > >
specialization of cnl::catalan for cnl::fixed_point
template<>
constexpr float catalan< float > {0.915965594177219015054603514932384110774f}
specialization of cnl::catalan for float
template<>
constexpr long double catalan< long double > {0.915965594177219015054603514932384110774L}
specialization of cnl::catalan for long double
template<typename T >
constexpr T e {_impl::deleted_fn<T>()}
partial implementation of P0631
template<>
constexpr double e< double > {2.7182818284590452354}
specialization of cnl::e for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > e< fixed_point< Rep, Exponent > >
specialization of cnl::e for cnl::fixed_point
template<>
constexpr float e< float > {2.7182818284590452354f}
specialization of cnl::e for float
template<>
constexpr long double e< long double > {2.718281828459045235360287471352662498L}
specialization of cnl::e for long double
template<typename T >
constexpr T egamma {_impl::deleted_fn<T>()}
approximation of the Euler–Mascheroni constant; primary variable template
template<>
constexpr double egamma< double > {0.5772156649015328606065120900824024}
specialization of cnl::egamma for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > egamma< fixed_point< Rep, Exponent > >
specialization of cnl::egamma for cnl::fixed_point
template<>
constexpr float egamma< float > {0.5772156649015328606065120900824024f}
specialization of cnl::egamma for float
template<>
constexpr long double egamma< long double > {0.5772156649015328606065120900824024L}
specialization of cnl::egamma for long double
template<typename T >
constexpr T glaisher {_impl::deleted_fn<T>()}
approximation of the Glaisher–Kinkelin constant; primary variable template
template<>
constexpr double glaisher< double > {1.282427129100622636875342568869791727}
specialization of cnl::glaisher for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > glaisher< fixed_point< Rep, Exponent > >
specialization of cnl::glaisher for cnl::fixed_point
template<>
constexpr float glaisher< float > {1.282427129100622636875342568869791727f}
specialization of cnl::glaisher for float
template<>
constexpr long double glaisher< long double > {1.282427129100622636875342568869791727L}
specialization of cnl::glaisher for long double
template<typename T >
constexpr T invpi {_impl::deleted_fn<T>()}
approximation of 1/pi; primary variable template
template<>
constexpr double invpi< double > {0.31830988618379067154}
specialization of cnl::invpi for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > invpi< fixed_point< Rep, Exponent > >
specialization of cnl::invpi for cnl::fixed_point
template<>
constexpr float invpi< float > {0.31830988618379067154f}
specialization of cnl::invpi for float
template<>
constexpr long double invpi< long double > {0.318309886183790671537767526745028724L}
specialization of cnl::invpi for long double
template<typename T >
constexpr T invsqrt2 {sqrt2<T>/2}
approximation of the inverse of the square root of 2, 1/sqrt(2); primary variable template
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > invsqrt2< fixed_point< Rep, Exponent > >
specialization of cnl::invsqrt2 for cnl::fixed_point
template<typename T >
constexpr T invsqrt3 {_impl::deleted_fn<T>()}
approximation of the inverse of the square root of 3, 1/sqrt(3); primary variable template
template<>
constexpr double invsqrt3< double > {0.57735026918962576450914878050195745564760175127013}
specialization of cnl::invsqrt3 for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > invsqrt3< fixed_point< Rep, Exponent > >
specialization of cnl::invsqrt3 for cnl::fixed_point
template<>
constexpr float invsqrt3< float > {0.57735026918962576450914878050195745564760175127013f}
specialization of cnl::invsqrt3 for float
template<>
constexpr long double invsqrt3< long double >
specialization of cnl::invsqrt3 for long double
template<typename T >
constexpr T invsqrtpi {_impl::deleted_fn<T>()}
approximation of 1/sqrt(pi); primary variable template
template<>
constexpr double invsqrtpi< double > {0.564189583547756286948079451560772585844050629329}
specialization of cnl::invsqrtpi for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > invsqrtpi< fixed_point< Rep, Exponent > >
specialization of cnl::invsqrtpi for cnl::fixed_point
template<>
constexpr float invsqrtpi< float > {0.564189583547756286948079451560772585844050629329f}
specialization of cnl::invsqrtpi for float
template<>
constexpr long double invsqrtpi< long double >
specialization of cnl::invsqrtpi for long double
template<typename T >
constexpr T ln10 {_impl::deleted_fn<T>()}
approximation of the natural logarithm of 10, ln(10); primary variable template
template<>
constexpr double ln10< double > {2.30258509299404568402}
specialization of cnl::ln10 for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > ln10< fixed_point< Rep, Exponent > >
specialization of cnl::ln10 for cnl::fixed_point
template<>
constexpr float ln10< float > {2.30258509299404568402f}
specialization of cnl::ln10 for float
template<>
constexpr long double ln10< long double > {2.302585092994045684017991454684364208L}
specialization of cnl::ln10 for long double
template<typename T >
constexpr T ln2 {_impl::deleted_fn<T>()}
approximation of the natural logarithm of 2, ln(2); primary variable template
template<>
constexpr double ln2< double > {0.69314718055994530942}
specialization of cnl::ln2 for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > ln2< fixed_point< Rep, Exponent > >
specialization of cnl::ln2 for cnl::fixed_point
template<>
constexpr float ln2< float > {0.69314718055994530942f}
specialization of cnl::ln2 for float
template<>
constexpr long double ln2< long double > {0.693147180559945309417232121458176568L}
specialization of cnl::ln2 for long double
template<typename T >
constexpr T log10e {_impl::deleted_fn<T>()}
approximation of the decimal logarithm of e, log10(e); primary variable template
template<>
constexpr double log10e< double > {0.43429448190325182765}
specialization of cnl::log10e for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > log10e< fixed_point< Rep, Exponent > >
specialization of cnl::log10e for cnl::fixed_point
template<>
constexpr float log10e< float > {0.43429448190325182765f}
specialization of cnl::log10e for float
template<>
constexpr long double log10e< long double > {0.434294481903251827651128918916605082L}
specialization of cnl::log10e for long double
template<typename T >
constexpr T log2e {_impl::deleted_fn<T>()}
approximation of the binary logarithm of e, log2(e); primary variable template
template<>
constexpr double log2e< double > {1.4426950408889634074}
specialization of cnl::log2e for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > log2e< fixed_point< Rep, Exponent > >
specialization of cnl::log2e for cnl::fixed_point
template<>
constexpr float log2e< float > {1.4426950408889634074f}
specialization of cnl::log2e for float
template<>
constexpr long double log2e< long double > {1.442695040888963407359924681001892137L}
specialization of cnl::log2e for long double
template<typename T >
constexpr T phi {_impl::deleted_fn<T>()}
approximation of the golden ratio; primary variable template
template<>
constexpr double phi< double > {1.6180339887498948482045868343656381}
specialization of cnl::phi for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > phi< fixed_point< Rep, Exponent > >
specialization of cnl::phi for cnl::fixed_point
template<>
constexpr float phi< float > {1.6180339887498948482045868343656381f}
specialization of cnl::phi for float
template<>
constexpr long double phi< long double > {1.6180339887498948482045868343656381L}
specialization of cnl::phi for long double
template<typename T >
constexpr T pi {_impl::deleted_fn<T>()}
approximation of pi; primary variable template
template<>
constexpr double pi< double > {3.14159265358979323846}
specialization of cnl::pi for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > pi< fixed_point< Rep, Exponent > >
specialization of cnl::pi for cnl::fixed_point
template<>
constexpr float pi< float > {3.14159265358979323846f}
specialization of cnl::pi for float
template<>
constexpr long double pi< long double > {3.141592653589793238462643383279502884L}
specialization of cnl::pi for long double
template<typename T >
constexpr T radian {_impl::deleted_fn<T>()}
approximation of a radian in degrees, 180/pi; primary variable template
template<>
constexpr double radian< double > {57.295779513082320876798154814105170332405472466564}
specialization of cnl::radian for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > radian< fixed_point< Rep, Exponent > >
specialization of cnl::radian for cnl::fixed_point
template<>
constexpr float radian< float > {57.295779513082320876798154814105170332405472466564f}
specialization of cnl::radian for float
template<>
constexpr long double radian< long double >
specialization of cnl::radian for long double
template<typename T >
constexpr T sqrt2 {_impl::deleted_fn<T>()}
approximation of the square root of 2, sqrt(2); primary variable template
template<>
constexpr double sqrt2< double > {1.41421356237309504880}
specialization of cnl::sqrt2 for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > sqrt2< fixed_point< Rep, Exponent > >
specialization of cnl::sqrt2 for cnl::fixed_point
template<>
constexpr float sqrt2< float > {1.41421356237309504880f}
specialization of cnl::sqrt2 for float
template<>
constexpr long double sqrt2< long double > {1.414213562373095048801688724209698079L}
specialization of cnl::sqrt2 for long double
template<typename T >
constexpr T sqrt3 {_impl::deleted_fn<T>()}
approximation of the square root of 3, sqrt(3); primary variable template
template<>
constexpr double sqrt3< double >
specialization of cnl::sqrt3 for double
template<typename Rep , int Exponent>
constexpr fixed_point< Rep, Exponent > sqrt3< fixed_point< Rep, Exponent > >
specialization of cnl::sqrt3 for cnl::fixed_point
template<>
constexpr float sqrt3< float > {1.73205080756887729352744634150587236694280525381038062805580f}
specialization of cnl::sqrt3 for float
template<>
constexpr long double sqrt3< long double >
specialization of cnl::sqrt3 for long double
Detailed Description
compositional numeric library
Typedef Documentation
elastic_number
template<int Digits, int Exponent = 0, class Narrowest = signed> using cnl::elastic_number = typedef fixed_point<elastic_integer<Digits, Narrowest>, Exponent>
literal real number approximation that uses fixed-point arithmetic and auto-widens to avoid overflow
Template Parameters
Digits the total number of integer and fractional digits stored
Exponent the exponent by which the number is scale
Narrowest the most narrow integer type to use to represent values
See also
elastic_integer
multiprecision
template<unsigned NumDigits = digits<int>::value> using cnl::multiprecision = typedef signed_multiprecision<NumDigits>
alias to a signed, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::signed_multiprecision, cnl::unsigned_multiprecision
signed_multiprecision
template<unsigned NumDigits = digits<int>::value> using cnl::signed_multiprecision = typedef _sized_integer_impl::number<NumDigits+1, _bmp::signed_magnitude>
alias to a signed, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::unsigned_multiprecision, cnl::multiprecision
static_integer
template<int Digits = digits<int>::value, class RoundingTag = nearest_rounding_tag, class OverflowTag = trapping_overflow_tag, class Narrowest = int> using cnl::static_integer = typedef _impl::static_integer<Digits, RoundingTag, OverflowTag, Narrowest>
a general-purpose integer type
Template Parameters
Digits number of binary digits
OverflowTag behavior exhibited on out-of-range conditions
RoundingTag behavior exhibited on precision loss
Narrowest narrowest integer with which to represent the value
See also
cnl::static_number
static_number
template<int Digits, int Exponent = 0, class RoundingTag = nearest_rounding_tag, class OverflowTag = trapping_overflow_tag, class Narrowest = signed> using cnl::static_number = typedef fixed_point< _impl::static_integer<Digits, RoundingTag, OverflowTag, Narrowest>, Exponent>
a general-purpose fixed-point real number type
Template Parameters
Digits number of binary digits
Exponent the exponent used to scale the integer value
OverflowTag behavior exhibited on out-of-range conditions
RoundingTag behavior exhibited on precision loss
Narrowest narrowest integer with which to represent the value
See also
cnl::static_integer
unsigned_multiprecision
template<unsigned NumDigits = digits<unsigned>::value> using cnl::unsigned_multiprecision = typedef _sized_integer_impl::number<NumDigits, _bmp::unsigned_magnitude>
alias to an unsigned, fixed-size Boost.Multiprecision type suitable for instantiating cnl::fixed_point
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::signed_multiprecision, cnl::multiprecision
Function Documentation
abs()
template<typename Rep , int Exponent, int Radix> constexpr auto cnl::abs (fixed_point< Rep, Exponent, Radix > const & x) -> decltype(-x) noexcept
absolute value
Parameters
x input parameter
Returns
|x|
See also
std::vector
exp2()
template<class Rep , int Exponent> constexpr fixed_point<Rep, Exponent> cnl::exp2 (fixed_point< Rep, Exponent > x)
Calculates exp2(x), i.e. 2^xAccurate to 1LSB for up to 32 bit underlying representation.
Template Parameters
x the input value as a fixed_point
Returns
the result of the exponential, in the same representation as x
make_elastic_number() [1/2]
template<typename Narrowest = int, CNL_IMPL_CONSTANT_VALUE_TYPE Value = 0> constexpr elastic_number< _impl::max(digits<constant<Value>>::value-trailing_bits(Value), 1), trailing_bits(Value), Narrowest> cnl::make_elastic_number (constant< Value >)
generate an cnl::elastic_number object of given value
Template Parameters
Narrowest the narrowest type to use as storage in the resultant cnl::elastic_number object
Integral the type of Value
Value the integer number to be represented
Returns
the given value to be represented using an cnl::elastic_number type
Note
The return type is guaranteed to be no larger than is necessary to represent the value.
Example
To define an int-sized object using make_elastic_number and cnl::constant
// std::uint8_t specifies the type of const_integer - not elastic
constexpr auto n = make_elastic_number(constant<0xAA>{});
static_assert(n==0xAA, "n now has the value, 1024");
static_assert(std::is_same<decltype(n), elastic_number<7, 1, int> const>::value, "by default make_elastic_number uses the most efficient type it can");
make_elastic_number() [2/2]
template<class Narrowest = int, class Integral = int> constexpr elastic_number<numeric_limits<Integral>::digits, 0, Narrowest> cnl::make_elastic_number (Integral value)
generate an cnl::elastic_number object of given value
Template Parameters
Narrowest the most narrow storage type of the resultant cnl::elastic_number object
Integral the type of value
Parameters
value the value with which to initialize the elastic_number object
Note
The return type is guaranteed to be no larger than is necessary to represent the value.
Example
To define a byte-sized object using make_elastic_number and _c:
constexpr auto n = make_elastic_number<char>(constant<1536>{});
static_assert(n==1536, "n now has the value, 1536");
static_assert(std::is_same<decltype(n), elastic_number<2, 9, char> const>::value, "by default make_elastic_number uses the most efficient type it can");
make_fixed_point()
template<typename Value > constexpr auto cnl::make_fixed_point (Value const & value) -> cnl::from_value_t<fixed_point<Value, 0>, Value>
makes a fixed_point object from a given value
Template Parameters
Value the type of the value that is to be made into a fixed_point value
Parameters
value the value from which to make the fixed_point object
Note
This function is deprecated after C++17 in favor of class template deduction.
multiply()
template<class Lhs , class Rhs > constexpr auto cnl::multiply (Lhs const & lhs, Rhs const & rhs) -> typename _multiply_impl::params<Lhs, Rhs>::result_type
calculates the product of two fixed_point factors
Parameters
lhs,rhs the factors
Returns
product: lhs * rhs
Note
This function multiplies the values without performing any additional scaling or conversion.
References to_rep().
quotient()
template<class Quotient = _impl::default_quotient_tag, class Dividend , class Divisor > constexpr auto cnl::quotient (Dividend const & dividend, Divisor const & divisor) -> typename _impl::result<Quotient, Dividend, Divisor>::type
calculates the quotient of two fixed_point values
Template Parameters
Quotient the desired fixed_point type of quotient; by default, a value which minimizes the chances of overflow or precision loss
Dividend the dividend (top number) of the division
Divisor the divisor (bottom number) of the division
Parameters
dividend,divisor dividend and divisor
Returns
quotient: dividend / divisor
Note
When specifying the Quotient, ensure that there is enough capacity to perform a widened division operation and store the quotient.
A widened division is one where the quotient has as many integer digits as the dividend's integer digits plus the divisor's fractional digits and as many fractional digits as the dividend's fractional digits plus the divisor's integer digits.
Referenced by cnl::fixed_point< Rep, Exponent, Radix >::fixed_point(), and to_rep().
sqrt()
template<typename Rep , int Exponent, int Radix> constexpr fixed_point<Rep, Exponent, Radix> cnl::sqrt (fixed_point< Rep, Exponent, Radix > const & x)
calculates the square root of a fixed_point value
Parameters
x input parameter
Returns
square root of x
Note
This function is a placeholder implementation with poor run-time performance characteristics.
See also
multiply
References to_rep().
to_rep()
template<class Number > constexpr Number cnl::to_rep (Number const & number)
Returns the value encapsulated in number.
Parameters
number the 'outer' object
Returns
the 'inner' value
See also
from_rep, from_value
Variable Documentation
e
template<typename T > constexpr T cnl::e {_impl::deleted_fn<T>()}
partial implementation of P0631
approximation of e; primary variable template