author = "John McFarlane"
breathe_default_project = "cnl"
breathe_domain_by_extension = {"h": "cpp"}
breathe_projects = {"cnl": "../xml"}
copyright = "2020, John McFarlane"
default_role = "cpp:any"
exclude_patterns = []
extensions = ["breathe"]
highlight_language = "c++"
html_theme = "alabaster"
language = "en"
primary_domain = "cpp"
project = "CNL - Compositional Numeric Library"
pygments_style = "sphinx"
release = "0.0.0"
