set(MISC_FLAGS "/W4 /WX /errorReport:prompt /nologo /wd4307")

set(EXCEPTION_ENABLED_FLAGS "/GR /EHsc")
set(EXCEPTION_DISABLED_FLAGS "/GR- -DBOOST_NO_EXCEPTIONS -DBOOST_NO_RTTI")

set(INT128_ENABLED_FLAGS "")
set(INT128_DISABLED_FLAGS "")

set(SAMPLE_CXX_FLAGS "/wd4018")
