#!/usr/bin/env bash

# installs conan dependencies in working directory;
# to be invoked prior to CMake configuration step

set -euo pipefail

conan profile new \
  --detect \
  default

conan profile update \
  settings.compiler.libcxx=libstdc++11 \
  default
