#!/usr/bin/env bash

# specialised alternative to init-build-clang-libc++ runs Clang-Tidy

set -euo pipefail

script_dir=$(
  cd "$(dirname "$0")"
  pwd
)

"${script_dir}/init-build-clang-libc++" \
  --options clang_tidy="True" \
  "$@"
