#!/usr/bin/env bash

# specialised alternative to init-build-gcc tailored to build armv7

set -euo pipefail

PROJECT_DIR=$(
  cd "$(dirname "$0")"/../..
  pwd
)

"${PROJECT_DIR}/test/scripts/init-build-gcc" \
  --profile "${PROJECT_DIR}/.github/conan/profiles/linux-gcc-10-armv7" \
  "$@"
