#!/usr/bin/env bash

# turn the (empty) working directory into a build environment;
# called in an empty build directory;
# called before `conan build`

# e.g.
# rm -rf ../build/* && ../test/scripts/init-build -s compiler=gcc -s compiler.version=12 -s compiler.libcxx=libstdc++11 && conan build ..

set -euo pipefail

cnl_dir=$(
  cd "$(dirname "$0")"/../..
  pwd
)

conan config install "${cnl_dir}/.github/conan/settings.yml"

# get dependencies ready
conan install \
  --build missing \
  --env CONAN_CMAKE_TOOLCHAIN_FILE="${cnl_dir}/test/toolchain/posix.cmake" \
  --profile "${cnl_dir}/.github/conan/profiles/linux" \
  "$@" \
  "${cnl_dir}"

# configure build system
conan build --configure "${cnl_dir}"
