#!/usr/bin/env bash

# prepares user environment for building CNL;
# called once before using init-build* scripts

set -euo pipefail

conan remote add \
  johnmcfarlane/cnl https://api.bintray.com/conan/johnmcfarlane/cnl
