#!/usr/bin/env bash

# specialised alternative to init-build-clang tailored to libc++

set -euo pipefail

PROJECT_DIR=$(
  cd "$(dirname "$0")"/../..
  pwd
)

"${PROJECT_DIR}/test/scripts/init-build-clang" \
  --env CONAN_CMAKE_TOOLCHAIN_FILE="${PROJECT_DIR}/test/toolchain/clang-libc++.cmake" \
  --profile "${PROJECT_DIR}/.github/conan/profiles/linux-clang" \
  "$@"
