#!/usr/bin/env bash

# specialised alternative to init-build-clang tailored to run MSan and ASan

set -euo pipefail

script_dir=$(
  cd "$(dirname "$0")"
  pwd
)

"${script_dir}/init-build-clang" \
  --options sanitize=True \
  "$@"
