#!/usr/bin/env bash

# specialised alternative to init-build-clang runs Clang-Tidy

set -euo pipefail

script_dir=$(
  cd "$(dirname "$0")"
  pwd
)

"${script_dir}/init-build-clang" \
  --options clang_tidy="True" \
  "$@"
