#!/usr/bin/env bash

# specialised alternative to init-build tailored to Clang toolchain

set -euo pipefail

export CC="${CC:-clang}"
export COMPILER=clang
export CXX="${CXX:-clang++}"
export SANITIZE="${SANITIZE:-False}"
export TOOLCHAIN="${TOOLCHAIN:-clang.cmake}"

script_dir=$(
  cd "$(dirname "$0")"
  pwd
)

"${script_dir}/init-build" "$@"
