#!/usr/bin/env bash

# specialised alternative to init-build tailored to Clang toolchain

set -euo pipefail

PROJECT_DIR=$(
  cd "$(dirname "$0")"/../..
  pwd
)

"${PROJECT_DIR}/test/scripts/init-build" \
  --profile "${PROJECT_DIR}/.github/conan/profiles/linux-clang" \
  --settings compiler.version=12 \
  "$@"
