#!/usr/bin/env bash

# run markdownlint linter over all markdown documents in project directory

set -euo pipefail

PROJECT_DIR=$(
  cd "$(dirname "$0")"/../..
  pwd
)

cd "${PROJECT_DIR}"

find "${PROJECT_DIR}" -name "*.md" | while read -r TEST; do
  mdl \
    --style "${PROJECT_DIR}/test/scripts/mdl.style" \
    "$TEST"
done

echo mdl success
