#!/usr/bin/env bash

# build and run tests;
# called after init-build* has prepared a build directory

# Example:
#   mkdir my-build-directory
#   cd my-build-directory
#   INT128=False TARGET=test-all CONAN_CMAKE_GENERATOR="Unix Makefiles" path/to/cnl/test/scripts/init-build
#   path/to/cnl/test/scripts/test

set -euo pipefail

PROJECT_DIR=$(
  cd "$(dirname "$0")"/../..
  pwd
)

conan build --build --test "${PROJECT_DIR}"
